"use client";

import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'zh' | 'en';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    zh: {
        "login": "登录",
        "username": "用户名",
        "password": "密码",
        "totp": "两步验证码 (可选)",
        "login_loading": "登录中...",
        "login_success": "登录成功",
        "login_failed": "登录失败",
        "user_or_pass_error": "用户名或密码错误",
        "totp_error": "两步验证码错误或已过期",
        "auth_failed": "认证失败，请重新登录",
        "sidebar_home": "首页",
        "sidebar_accounts": "账号管理",
        "sidebar_settings": "系统设置",
        "sidebar_tasks": "任务列表",
        "add_account": "添加账号",
        "add_task": "新建任务",
        "edit": "编辑",
        "run": "运行",
        "delete": "删除",
        "confirm_delete": "确定要删除吗？",
        "save": "保存",
        "cancel": "取消",
        "settings_desc": "一个完全使用 Antigravity 开发的 Telegram 自动发送消息/签到项目",
        "settings_title": "系统设置",
        "logout": "退出登录",
        "connected": "已连接",
        "account_status_checking": "检测中",
        "account_status_invalid": "登录失效",
        "account_status_error": "检测失败",
        "account_relogin_required": "账号状态失效，请重新登录",
        "relogin_account": "重新登录",
        "logs": "日志",
        "remove": "移除",
        "edit_account": "编辑账号",
        "remark": "备注 (可选)",
        "remark_placeholder": "如：工作号/备用号",
        "session_name": "账号名",
        "phone_number": "手机号码",
        "login_code": "登录验证码",
        "login_code_placeholder": "5 位数字",
        "two_step_pass": "两步验证 (Cloud Password)",
        "two_step_placeholder": "未设置请留空",
        "proxy": "SOCKS5 代理 (可选)",
        "proxy_placeholder": "socks5://ip:port 或 socks5://user:pass@ip:port",
        "confirm_connect": "确认保存",
        "login_method_phone": "验证码登录",
        "login_method_qr": "扫码登录",
        "qr_start": "获取二维码",
        "qr_refresh": "刷新二维码",
        "qr_cancel": "取消扫码",
        "qr_waiting": "等待扫码",
        "qr_scanned": "已扫码待确认",
        "qr_success": "登录成功",
        "qr_failed": "登录失败",
        "qr_expired": "二维码已过期",
        "qr_tip": "打开 Telegram 扫描二维码登录",
        "qr_expires_in": "有效期 {seconds}s",
        "next_step": "下一步",
        "back": "返回",
        "send_code": "发送验证码",
        "safety_verify": "安全验证",
        "code_sent": "验证码已发送至您的手机/Telegram 客户端",
        "running_logs": "运行日志",
        "logs_summary": "最近 {count} 条记录（{days} 天历史）",
        "export_logs": "导出日志",
        "no_logs": "暂无运行日志",
        "task_label": "任务",
        "bot_reply": "机器人回复",
        "task_exec_success": "执行成功",
        "task_exec_failed": "执行失败",
        "close": "关闭",
        "success": "成功",
        "failure": "失败",
        "task_details": "任务详情",
        "manage_tasks_for": "管理账号的所有自动签到任务",
        "refresh_chats": "刷新 Chat 列表",
        "loading": "加载中...",
        "no_tasks": "配置第一个签到目的地",
        "no_tasks_desc": "选择一个频道或群组，设定动作与时间点",
        "create_task": "创建签到任务",
        "edit_task": "编辑任务",
        "task_name": "任务名称",
        "task_name_placeholder": "例如: linuxdo_sign",
        "task_name_required": "请填写任务名称",
        "cron_required": "请填写 CRON 表达式",
        "range_required": "请填写完整的时间段",
        "chat_required": "请至少添加一个 Chat",
        "select_chat_error": "请选择一个 Chat",
        "add_action_error": "请至少添加一个动作",
        "load_failed": "加载失败",
        "account_session_invalid": "账号登录已失效，请重新登录",
        "create_success": "任务创建成功",
        "create_failed": "创建失败",
        "associated_account": "关联账号",
        "define_global_rules": "定义全局签到规则，可以应用到多个目标频道",
        "basic_config": "基本配置",
        "scheduling_mode": "调度模式",
        "mode_range": "随机时段",
        "mode_fixed": "Cron 定时",
        "random_range_default": "随机时间段 (默认)",
        "random_range_desc": "系统将在设定的时间段内随机选择一个时间点执行任务，避免被检测为机器人。",
        "fixed_cron_desc": "使用标准 Cron 表达式精确指定执行时间，格式：分 时 日 月 周（如 0 9 * * * 代表每天 09:00）",
        "cron_expression": "Cron 表达式",
        "cron_placeholder": "0 9 * * *",
        "start_time": "开始时间",
        "end_time": "结束时间",
        "start_label": "开始",
        "end_label": "结束",
        "time_range": "时间范围",
        "target_chat_config": "目标聊天配置",
        "add_chat": "添加聊天",
        "no_target_chat": "还没有目标聊天",
        "actions_count": "动作",
        "id_label": "ID",
        "deploy_task": "创建任务",
        "configure_target_chat": "配置目标聊天",
        "select_target_chat": "选择目标聊天",
        "select_chat_placeholder": "请选择服务器中的聊天...",
        "action_sequence_title": "任务动作序列",
        "add_sign_action": "添加签到动作",
        "no_actions_hint": "点击上方按钮添加第一个动作，如发送 \"/checkin\"",
        "confirm_add": "确认添加",
        "random_range_recommend": "随机时间段 (推荐)",
        "fixed_time_cron": "固定时间 (Cron)",
        "sign_time_cron": "签到时间 (Cron 表达式)",
        "cron_example": "示例: 0 9 * * * (早上 9:00)",
        "refresh_list": "刷新列表",
        "refresh_chat_title": "从 Telegram 重新获取对话",
        "select_from_list": "从列表选择...",
        "search_chat": "搜索会话",
        "search_chat_placeholder": "输入名称 / 用户名 / Chat ID",
        "searching": "搜索中...",
        "search_no_results": "未找到匹配会话",
        "ai_vision_mode": "AI 识图模式",
        "ai_logic_solver": "AI 计算模式",
        "ai_vision_click_mode": "AI 识图后点击按钮",
        "ai_vision_send_mode": "AI 识图后发送文本",
        "ai_logic_send_mode": "AI 计算题后发送文本",
        "ai_logic_click_mode": "AI 计算题后点击按钮",
        "sign_time": "签到时间 (CRON)",
        "random_delay": "随机延迟 (分钟)",
        "action_interval": "动作间隔 (秒)",
        "select_chat": "选择频道/群组",
        "manual_chat_id": "或手动输入聊天 ID",
        "delete_after": "消息删除延迟 (秒, 可选)",
        "action_sequence": "有序动作序列",
        "deploy_now": "立即部署",
        "save_changes": "保存修改",
        "add_action": "添加动作",
        "change_username": "修改用户名",
        "new_username": "新用户名",
        "current_password": "当前密码",
        "change_password": "修改密码",
        "old_password": "旧密码",
        "new_password": "新密码",
        "confirm_new_password": "确认新密码",
        "2fa_settings": "两步验证",
        "2fa_enable_desc": "开启后，登录时除了密码，还需要输入身份验证器里的 6 位验证码。",
        "start_setup": "开始设置",
        "scan_qr": "扫描二维码",
        "scan_qr_desc": "用 Google Authenticator 等身份验证器扫描上方二维码。",
        "backup_secret": "备用密钥",
        "verify_code": "验证代码",
        "verify": "验证",
        "disable_2fa": "关闭两步验证",
        "ai_config": "AI 配置",
        "api_key": "API 密钥",
        "base_url": "基础 URL (Base URL)",
        "model": "预设模型 (Model)",
        "test_connection": "连接测试",
        "global_settings": "全局参数",
        "sign_interval": "签到间隔 (秒)",
        "sign_interval_desc": "设置将应用于所有启用全局间隔的任务",
        "log_retention": "日志保留天数",
        "save_global_params": "保存全局参数",
        "tg_api_config": "Telegram API",
        "restore_default": "恢复默认凭据",
        "api_id": "API ID",
        "api_hash": "API Hash",
        "apply_api_config": "应用 API 配置",
        "tg_config_warning": "修改后，现有账号的登录可能失效。仅在添加账号遇到 API 兼容问题时再自定义。",
        "backup_migration": "备份与迁移",
        "export_config": "导出全部配置",
        "export_desc": "包含全部任务和账号基础信息。文件含敏感信息，请妥善保管。",
        "download_json": "下载配置文件",
        "import_config": "导入配置内容",
        "paste_json": "或在此粘贴 JSON 内容",
        "overwrite_conflict": "覆盖同名任务",
        "execute_import": "导入",
        "upload_json": "选择 JSON 文件",
        "process_successful": "执行成功",
        "process_error": "执行出错",
        "warning_notice": "警告提示",
        "connect_success": "连接成功",
        "action_send_text": "发送文本",
        "action_send_dice": "发送骰子",
        "action_click_button": "点击按钮",
        "action_ai_vision": "AI 图片识别",
        "action_ai_logic": "AI 计算题",
        "action_ai_vision_click": "AI 识图后点按钮",
        "action_ai_vision_send": "AI 识图后发文本",
        "action_ai_logic_send": "AI 计算后发文本",
        "action_ai_logic_click": "AI 计算后点按钮",
        "action_type_label": "动作 {index} 类型",
        "dice_type_label": "骰子类型",
        "ai_auto_hint": "AI 自动处理，无需额外配置",
        "ai_hint_4": "等待机器人发送含图片及按钮的消息，AI 识图后自动点击对应选项",
        "ai_vision_question_label": "AI 提示语（可选）",
        "ai_vision_question_placeholder": "补充说明题目要求，留空则自动从消息 caption 提取",
        "ai_hint_5": "等待机器人发送含计算题的文本消息，AI 解题后自动发送答案",
        "ai_hint_6": "等待机器人发送含图片的消息，AI 识别图片中的文字后自动发送",
        "ai_hint_7": "等待机器人发送含计算题的文本消息，AI 解题后自动点击对应按钮",
        "first_action_must_be_send": "第一个动作必须为「发送文本」或「发送骰子」",
        "test_send_label": "测试发送消息",
        "test_send_btn": "发送测试",
        "test_send_hint": "消息将通过所选账号实际发出，可用于验证 Chat ID 是否正确",
        "test_send_success": "测试消息已发送",
        "test_send_failed": "测试发送失败",
        "test_chat_btn": "测试执行",
        "test_chat_success": "测试执行完成",
        "test_chat_failed": "测试执行失败",
        "edit_chat_btn": "编辑目标聊天",
        "task_next_run": "下次执行",
        "next_run_today": "今天",
        "next_run_tomorrow": "明天",
        "next_run_in_window": "进行中",
        "next_run_paused": "已暂停",
        "next_run_unknown": "—",
        "ignore_case": "忽略大小写",
        "push_telegram": "TG Bot 通知",
        "push_forward": "转发到群组",
        "push_bark": "Bark 推送",
        "push_custom": "自定义 URL",
        "push_continue": "继续对话",
        "bark_url_label": "Bark URL",
        "forward_chat_id_label": "转发目标 Chat ID",
        "continue_chat_id_label": "继续对话 Chat ID",
        "placeholder_msg": "发送的消息内容...",
        "placeholder_btn": "要点击的按钮上的文字...",
        "manual_id_placeholder": "手动输入 Chat ID...",
        "delete_after_placeholder": "发送后多久自动删除指令...",
        "no_data": "暂无数据",
        "account_name_phone_required": "请填写账号名称和手机号",
        "account_name_duplicate": "账号名已存在，请更换",
        "send_code_failed": "发送验证码失败",
        "login_code_required": "请输入验证码",
        "account_name_required": "请输入账号名称",
        "verify_failed": "验证失败",
        "confirm_delete_account": "确定要删除账号 {name} 吗？",
        "account_deleted": "账号已删除",
        "delete_failed": "删除失败",
        "save_failed": "保存失败",
        "qr_create_failed": "生成二维码失败",
        "cancel_failed": "取消失败",
        "logs_fetch_failed": "获取日志失败",
        "clear_logs": "清空日志",
        "clear_logs_confirm": "确定要清空账号 {name} 的日志吗？",
        "clear_logs_success": "日志已清空",
        "clear_logs_failed": "清空日志失败",
        "qr_expired_not_found": "二维码已过期或不存在",
        "qr_login_failed": "扫码登录失败",
        "qr_status_failed": "获取扫码状态失败",
        "qr_password_required": "需要两步验证密码",
        "qr_password_missing": "请输入两步验证密码",
        "qr_password_invalid": "两步验证密码错误",
        "qr_password_submit": "提交验证",
        "account_name_placeholder": "字母、数字或中文",
        "phone_number_placeholder": "+86 138 0000 0000",
        "qr_alt": "二维码",
        "task_deleted": "任务 {name} 已删除",
        "task_run_failed": "任务运行失败",
        "task_run_success": "任务 {name} 运行成功",
        "account_name_prompt": "请输入账号名称",
        "status_active": "启用",
        "status_paused": "暂停",
        "task_schedule": "执行时间",
        "task_channels": "目标聊天",
        "task_hits": "{count} 个聊天",
        "task_last_run": "最近执行",
        "task_run_logs_title": "任务运行日志: {name}",
        "task_history_logs": "任务历史日志",
        "task_history_logs_title": "任务历史日志: {name}",
        "task_history_empty": "暂无签到历史",
        "task_history_no_flow": "该记录没有流程详情（旧版本可能仅保存结果）",
        "task_history_truncated": "日志过长，已截断。原始行数: {count}",
        "task_history": "签到历史",
        "task_history_title": "签到历史 · {name}",
        "task_run_detail_title": "执行详情 · {name}",
        "view_live_logs": "查看实时日志",
        "task_logs_empty": "暂无执行日志",
        "manual_run": "立即签到",
        "start_task": "开启定时签到",
        "stop_task": "停止定时签到",
        "task_started": "已开启定时签到: {name}",
        "task_stopped": "已停止定时签到: {name}",
        "task_toggle_failed": "切换任务状态失败",
        "logs_waiting": "等待日志输出...",
        "task_running": "正在运行中...",
        "task_done": "任务执行完成",
        "task_executing": "正在执行...",
        "chats_refreshed": "会话列表已刷新",
        "refresh_failed": "刷新失败",
        "search_failed": "搜索失败",
        "chat_id_numeric": "手动输入的 Chat ID 必须是数字",
        "update_success": "任务更新成功",
        "update_failed": "更新失败",
        "chat_default_name": "会话 {id}",
        "form_incomplete": "请填写完整信息",
        "username_changed": "用户名修改成功",
        "change_failed": "修改失败",
        "password_mismatch": "两次输入的密码不一致",
        "password_changed": "密码修改成功",
        "default_password_warning": "你仍在使用默认密码 admin123，任何人都能登录这个面板。请立即修改密码。",
        "setup_failed": "准备失败",
        "two_factor_enabled": "两步验证已启用",
        "enable_failed": "启用失败",
        "two_factor_disable_prompt": "请输入两步验证码以停用：",
        "two_factor_disabled": "两步验证已停用",
        "disable_failed": "停用失败",
        "export_success": "配置导出成功",
        "export_failed": "导出失败",
        "import_empty": "请粘贴配置内容",
        "import_success": "导入成功",
        "import_failed": "导入失败",
        "ai_save_success": "AI 配置保存成功",
        "connect_failed": "连接失败",
        "test_failed": "测试出错",
        "confirm_delete_ai": "确定要删除 AI 配置吗？",
        "ai_delete_success": "AI 配置已删除",
        "global_save_success": "全局设置保存成功",
        "telegram_save_success": "Telegram 配置保存成功",
        "confirm_reset_telegram": "确定要重置 Telegram 配置为默认值吗？",
        "config_reset": "配置已重置",
        "operation_failed": "操作失败",
        "new_username_placeholder": "新用户名",
        "current_password_placeholder": "验证当前密码",
        "status_enabled": "已开启",
        "status_disabled": "未开启",
        "totp_code_placeholder": "6 位数字",
        "delete_ai_config": "删除 AI 配置",
        "ai_base_url_placeholder": "https://api.openai.com/v1",
        "api_key_keep_hint": "留空表示保持当前 API 密钥不变",
        "sign_interval_placeholder": "留空则随机 1-120 秒",
        "data_dir": "数据目录",
        "data_dir_placeholder": "例如: /opt/tg-signpulse-data",
        "data_dir_desc": "用于保存 sessions、logs、数据库和任务数据",
        "data_dir_restart_hint": "修改后需重启后端服务才能生效。",
        "global_proxy": "全局代理",
        "global_proxy_placeholder": "socks5://127.0.0.1:1080 或 http://127.0.0.1:7890",
        "global_proxy_desc": "账号未单独设置代理时，登录、刷新会话和执行任务都使用这个代理。",
        "telegram_bot_notify": "Bot 通知",
        "telegram_bot_notify_desc": "任务失败或关键词命中时，通过你的 Telegram Bot 发送消息。",
        "telegram_bot_events_off_hint": "打开上方的「开启通知」后，这些设置才会生效。",
        "telegram_bot_master_switch": "开启通知",
        "telegram_login_notify": "登录通知",
        "telegram_login_notify_desc": "开启后每次登录都会发送登录 IP",
        "telegram_task_failure_notify": "任务执行失败通知",
        "telegram_task_failure_notify_desc": "开启后任务失败时发送最近运行日志",
        "telegram_task_success_notify": "任务执行成功通知",
        "telegram_task_success_notify_desc": "开启后任务成功时发送通知消息",
        "telegram_bot_token": "机器人 Token",
        "telegram_bot_token_placeholder": "从 BotFather 获取",
        "telegram_bot_chat_id": "通知 Chat ID",
        "telegram_bot_chat_id_placeholder": "如 123456789",
        "telegram_bot_thread_id": "通知话题 ID（可选）",
        "telegram_bot_thread_id_placeholder": "需要通知到指定话题时填写",
        "keyword_monitor": "关键词监听通知",
        "keyword_monitor_desc": "监听指定群组消息，命中关键词后推送消息内容和链接",
        "monitor_account": "监听账号",
        "select_account": "选择账号",
        "monitor_chat_id": "监听群组 Chat ID",
        "monitor_chat_id_placeholder": "例如: -1001234567890 或 @channel",
        "monitor_keywords": "关键词",
        "monitor_keywords_placeholder": "每行一个关键词，也支持逗号分隔",
        "match_mode": "匹配方式",
        "match_contains": "包含",
        "match_exact": "完全匹配",
        "match_regex": "正则",
        "push_channel": "推送方式",
        "custom_push_url": "自定义推送 URL",
        "custom_push_url_placeholder": "支持 POST JSON；也可使用 {title}、{body}、{url} 占位符发起 GET",
        "topic_id_label": "话题 / Thread ID（可选）",
        "topic_id_placeholder": "群组话题 ID，不需要则留空",
        "export_all_tasks": "导出全部任务到剪贴板",
        "copy_all_tasks_success": "全部任务已复制到剪贴板",
        "copy_all_tasks_empty": "当前账号没有可导出的任务",
        "copy_all_tasks_failed": "导出全部任务失败",
        "paste_all_tasks_success": "任务导入完成，已自动跳过重复任务",
        "relogin": "重新登录",
        "tg_api_id_placeholder": "来自 my.telegram.org",
        "tg_api_hash_placeholder": "来自 my.telegram.org",
        "github_repo": "GitHub 仓库",
        "totp_placeholder": "留空即跳过",
        "switch_to_english": "切换到英文",
        "switch_to_chinese": "切换到中文",
        "switch_to_light": "切换至日间模式",
        "switch_to_dark": "切换至夜间模式",
        "tab_tasks": "任务",
        "tab_accounts": "账号",
        "tab_settings": "设置",
        "main_navigation": "主导航",
        "confirm": "确定",
        "done": "完成",
        "optional": "可选",
        "required": "必填",
        "copy": "复制",
        "copied": "已复制",
        "refresh": "刷新",
        "retry": "重试",
        "more_actions": "更多操作",
        "unit_seconds": "秒",
        "unit_days": "天",
        "status_on": "开启",
        "status_off": "关闭",
        "configured": "已配置",
        "not_configured": "未配置",
        "not_set": "未设置",
        "next_short": "下次",
        "next_run_none": "暂无计划",
        "random_suffix": "随机",
        "schedule_daily": "每天 {time}",
        "schedule_daily_range": "每天 {start}–{end} 随机",
        "task_status": "定时执行",
        "delete_task": "删除任务",
        "delete_task_title": "删除任务「{name}」？",
        "delete_task_message": "删除后无法恢复。",
        "run_connection_lost": "与服务器的连接已断开，稍后可在签到历史中查看结果。",
        "run_result_success": "执行成功",
        "run_result_failed": "执行失败",
        "run_result_unknown": "执行结束",
        "today_summary": "今日签到",
        "summary_failed": "失败",
        "summary_pending": "待执行",
        "summary_success": "成功",
        "filter_account": "账号：{name}",
        "clear_filter": "清除筛选",
        "filter_empty": "没有符合条件的任务",
        "show_all": "显示全部",
        "load_failed_desc": "请确认后端服务正在运行，然后重试。",
        "empty_no_account_title": "先添加一个 Telegram 账号",
        "empty_no_account_desc": "用手机验证码或扫码登录，登录后就能创建签到任务。",
        "empty_no_task_title": "还没有签到任务",
        "empty_no_task_desc": "新建一个任务，选择要签到的聊天和执行时间。",
        "import_from_clipboard": "从剪贴板导入",
        "import_from_clipboard_desc": "粘贴之前导出的任务配置",
        "export_all": "导出全部任务",
        "export_all_desc": "复制任务配置到剪贴板，便于备份或迁移",
        "account_invalid_banner": "{name} 的登录已失效",
        "account_invalid_action": "该账号的任务无法执行，点此重新登录",
        "account_required": "请选择账号",
        "no_account_yet": "还没有账号，请先添加",
        "cron_fields_hint": "分 时 日 月 周",
        "cron_examples": "示例",
        "target_chats_count": "目标聊天（{count}）",
        "target_chats_hint": "任务会按顺序在这些聊天中执行签到动作。",
        "no_target_chat_desc": "添加频道、群组或机器人，并设置要执行的签到动作。",
        "chat_row_meta": "{count} 个动作",
        "test_chat_named": "测试 {name}",
        "edit_locked_hint": "任务名称和关联账号创建后不能修改。",
        "test_short": "测试",
        "save_success": "已保存",
        "field_chat": "聊天",
        "field_message": "消息内容",
        "field_button_text": "按钮文字",
        "chat_search_hint": "可按名称、用户名或 ID 搜索；列表里没有的聊天，直接填写下方的 ID。",
        "topic_id_short": "话题 ID",
        "action_sequence_count": "签到动作（{count}）",
        "action_sequence_hint": "动作按从上到下的顺序依次执行。",
        "remove_action": "删除动作 {index}",
        "remove_chat": "移除此聊天",
        "remove_chat_title": "移除「{name}」？",
        "account_task_count": "{count} 个任务",
        "home_headline_failed": "{count} 个任务今天失败",
        "home_headline_failed_one": "{count} 个任务今天失败",
        "home_headline_relogin": "{count} 个账号需要重新登录",
        "home_headline_relogin_one": "{count} 个账号需要重新登录",
        "home_headline_ok": "今天一切正常",
        "home_headline_no_account": "先添加一个 Telegram 账号",
        "home_headline_no_task": "还没有签到任务",
        "home_headline_error": "暂时连不上服务",
        "home_headline_filtered": "{name} 今天一切正常",
        "home_updated": "{time} 更新",
        "home_task_total": "共 {count} 个任务",
        "pulse_caption": "近 30 天 · 成功率 {rate}",
        "pulse_rate_title": "近 30 天成功率 · {count} 次执行",
        "pulse_rate_label": "近 30 天成功率",
        "pulse_today": "今天",
        "pulse_days_short": "30 天",
        "pulse_days_ago": "{count} 天前",
        "pulse_day_detail": "{date}：{up} 个成功，{down} 个失败",
        "pulse_day_empty": "{date}：没有执行记录",
        "pulse_label": "近 30 天每天的执行结果",
        "retry_run": "重试",
        "upcoming_title": "接下来",
        "upcoming_now": "现在",
        "upcoming_in_window": "{names} 正在随机时段内",
        "upcoming_empty": "今明两天没有要执行的任务",
        "upcoming_skip_warn": "{name} 需重新登录，否则会跳过",
        "account_ok": "正常",
        "account_failed_count": "{count} 个失败",
        "account_invalid_tasks": "{count} 个任务暂停执行，重新登录后自动恢复",
        "account_invalid_no_tasks": "重新登录后才能执行任务",
        "manage_accounts": "管理账号",
        "account_no_tasks": "还没有任务",
        "account_no_runs": "近 30 天还没有执行记录",
        "needs_relogin": "需重新登录",
        "account_invalid_title": "登录已失效",
        "account_invalid_desc": "Telegram 会话已过期或被注销，该账号的签到任务无法执行。重新登录即可恢复。",
        "account_status": "状态",
        "last_checked": "上次检查",
        "delete_account": "删除账号",
        "delete_account_title": "删除账号「{name}」？",
        "delete_account_message": "会删除该账号的登录会话，之后需要重新登录才能使用。",
        "delete_account_message_tasks": "该账号下还有 {count} 个任务，删除账号后这些任务将无法执行。",
        "account_saved": "账号信息已保存",
        "proxy_hint": "支持 socks5:// 或 http:// 格式，留空则使用全局代理。",
        "health_check": "检查账号状态",
        "health_check_short": "检查状态",
        "health_check_done": "账号状态已更新",
        "health_check_failed": "检查失败",
        "accounts_subtitle": "{count} 个账号",
        "accounts_subtitle_invalid": "{count} 个账号 · {invalid} 个需要重新登录",
        "accounts_footer": "点按账号可查看详情、重新登录或查看运行日志。",
        "field_account_name": "账号名",
        "field_phone": "手机号",
        "field_code": "验证码",
        "field_2fa": "两步验证",
        "field_proxy": "代理",
        "field_remark": "备注",
        "relogin_intro": "「{name}」的登录已失效，重新登录后任务会恢复执行。",
        "login_method": "登录方式",
        "login_phone_hint": "手机号需带国家代码，例如 +8613800138000。",
        "optional_settings": "可选设置",
        "login_optional_hint": "仅当 Telegram 账号开启了两步验证时才需要填写密码；代理留空则使用全局代理。",
        "login_qr_hint": "用已登录 Telegram 的手机扫描二维码。",
        "qr_steps": "打开 Telegram › 设置 › 设备 › 连接桌面设备",
        "resend_code": "重新发送",
        "confirm_login": "登录",
        "telegram_bot_test_required": "请先填写 Token 和 Chat ID",
        "telegram_bot_section_bot": "机器人",
        "telegram_bot_token_short": "Token",
        "telegram_bot_chat_id_short": "Chat ID",
        "telegram_bot_send_test": "发送测试消息",
        "telegram_bot_section_events": "通知内容",
        "appearance": "外观",
        "theme": "主题",
        "theme_system": "跟随系统",
        "theme_light": "浅色",
        "theme_dark": "深色",
        "language": "语言",
        "account_security": "账户与安全",
        "features": "功能",
        "data": "数据",
        "about": "关于",
        "built_at": "构建于",
        "software_update": "软件更新",
        "update_in_progress_short": "正在更新",
        "update_checking": "正在检查更新",
        "update_check_failed": "检查失败",
        "update_available_short": "有新版本",
        "update_latest_short": "已是最新",
        "update_available_title": "有新版本可用",
        "update_latest_version": "最新版本 v{version}",
        "update_new_build": "镜像仓库里有更新的构建",
        "update_latest_title": "已是最新版本",
        "update_unknown_title": "暂时无法确定是否有新版本",
        "update_unknown_desc": "连不上 GitHub 或镜像仓库，稍后再试",
        "update_check_disabled": "已通过 APP_UPDATE_CHECK 关闭检查更新",
        "update_check_failed_desc": "无法获取更新信息，请检查网络后重试",
        "update_checked_at": "上次检查：{time}",
        "update_view_changes": "查看更新内容",
        "update_restart_hint": "更新时面板会下载新版本并自动重启，期间大约 1 分钟无法访问，定时任务会在重启后恢复。",
        "update_local_build_hint": "当前镜像是本地构建的，更新后会改用镜像仓库中的版本。",
        "update_now": "立即更新",
        "update_try": "检查并更新",
        "update_recheck": "重新检查",
        "update_reload_page": "刷新页面",
        "update_confirm_title": "现在更新吗？",
        "update_confirm_message": "面板会下载新版本并重启，期间大约 1 分钟无法访问。",
        "update_step_pull": "下载新版本",
        "update_step_restart": "重启面板",
        "update_step_done": "完成",
        "update_restarting_desc": "面板正在重启，完成后页面会自动刷新",
        "update_rolled_back_desc": "新版本没能正常启动，已恢复到原来的版本",
        "update_timeout_desc": "等待时间较长，请稍后刷新页面查看结果",
        "update_start_failed": "更新失败，请稍后重试",
        "update_reloading": "更新完成，正在刷新页面",
        "update_tasks_running": "有任务正在运行，请等任务结束后再更新",
        "update_done_toast": "已更新到 v{version}",
        "update_manual_title": "在服务器上更新",
        "update_manual_desc": "在 docker-compose.yml 所在目录运行：",
        "update_manual_not_container": "没有找到面板所在的 Docker 容器，请按部署时的方式更新，例如拉取最新代码后重启。",
        "update_enable_title": "开启一键更新",
        "update_enable_desc": "在 docker-compose.yml 的 volumes 里加上这一行，然后重新部署：",
        "update_enable_risk": "挂载后面板可以管理这台机器上的 Docker，请使用强密码并开启两步验证。",
        "update_reason_disabled": "一键更新已通过 APP_SELF_UPDATE 关闭。",
        "update_reason_no_socket": "当前部署没有挂载 Docker socket，所以不能一键更新。",
        "update_reason_permission": "面板没有读写 Docker socket 的权限。",
        "update_reason_unreachable": "连不上 Docker，请确认 socket 路径或 DOCKER_HOST 设置。",
        "update_reason_not_container": "如果面板确实运行在容器中，可以用 APP_UPDATE_CONTAINER 指定容器名。",
        "update_reason_pinned": "容器使用的是固定摘要的镜像，请在 compose 中改用镜像标签后重新部署。",
        "update_reason_not_pullable": "镜像仓库里找不到当前镜像，面板没法自己下载新版本。如果是私有镜像，需要在服务器上登录镜像仓库后手动更新。",
        "update_pull_denied": "镜像仓库里找不到这个镜像，或者需要登录才能下载",
        "update_manual_rebuild_desc": "如果镜像是自己构建的，拉取最新代码后重新构建：",
        "needs_change": "需要修改",
        "default_password_title": "请修改默认密码",
        "logout_confirm": "退出登录？",
        "export_file_success": "配置文件已下载",
        "change_username_hint": "修改后，下次登录请使用新用户名。",
        "password_hint": "至少 6 位。",
        "confirm_password_short": "确认密码",
        "confirm_password_placeholder": "再次输入新密码",
        "verify_and_enable": "验证并开启",
        "2fa_disable_desc": "输入身份验证器中的 6 位验证码来关闭两步验证。关闭后，登录只需要密码。",
        "ai_config_desc": "用于 AI 识图和计算题动作，兼容 OpenAI 接口。",
        "ai_test_hint": "使用已保存的配置发送一次测试请求。",
        "sign_interval_short": "签到间隔",
        "log_retention_short": "日志保留",
        "tg_api_custom": "正在使用自定义凭据",
        "tg_api_default": "正在使用内置凭据",
        "tg_api_custom_short": "自定义",
        "tg_api_default_short": "默认",
        "tg_api_hint": "在 my.telegram.org 的 API development tools 中申请。",
        "import_desc": "导入前，建议先导出一份当前配置作为备份。",
        "overwrite_conflict_desc": "关闭时跳过同名任务，开启后用导入的内容替换。",
        "login_tagline": "Telegram 多账号自动签到",
        "login_fields_required": "请输入用户名和密码",
        "totp_short": "验证码",
        "totp_if_enabled": "未开启可不填"
    },
    en: {
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "totp": "TOTP Code (Optional)",
        "login_loading": "Logging in...",
        "login_success": "Login Successful",
        "login_failed": "Login Failed",
        "user_or_pass_error": "Invalid username or password",
        "totp_error": "Invalid or expired TOTP code",
        "auth_failed": "Authentication failed, please login again",
        "sidebar_home": "Home",
        "sidebar_accounts": "Accounts",
        "sidebar_settings": "System Settings",
        "sidebar_tasks": "Tasks",
        "add_account": "Add Account",
        "add_task": "New Task",
        "edit": "Edit",
        "run": "Run",
        "delete": "Delete",
        "confirm_delete": "Are you sure you want to delete?",
        "save": "Save",
        "cancel": "Cancel",
        "settings_desc": "A Telegram auto-sign/messaging project developed entirely using Antigravity",
        "settings_title": "System Settings",
        "logout": "Logout",
        "connected": "Connected",
        "account_status_checking": "Checking",
        "account_status_invalid": "Session Invalid",
        "account_status_error": "Check Failed",
        "account_relogin_required": "Account session is invalid, please re-login",
        "relogin_account": "Sign In Again",
        "logs": "Logs",
        "remove": "Remove",
        "edit_account": "Edit Account",
        "remark": "Remark (Optional)",
        "remark_placeholder": "e.g. Work/Backup",
        "session_name": "Name",
        "phone_number": "Phone Number",
        "login_code": "Login Code",
        "login_code_placeholder": "5 digits",
        "two_step_pass": "2FA (Cloud Password)",
        "two_step_placeholder": "Leave blank if not set",
        "proxy": "SOCKS5 Proxy (Optional)",
        "proxy_placeholder": "socks5://ip:port or socks5://user:pass@ip:port",
        "confirm_connect": "Confirm Save",
        "login_method_phone": "Code Login",
        "login_method_qr": "QR Login",
        "qr_start": "Get QR",
        "qr_refresh": "Refresh QR",
        "qr_cancel": "Cancel",
        "qr_waiting": "Waiting for scan",
        "qr_scanned": "Scanned, awaiting confirmation",
        "qr_success": "Login success",
        "qr_failed": "Login failed",
        "qr_expired": "QR expired",
        "qr_tip": "Open Telegram and scan the QR code to login",
        "qr_expires_in": "Expires in {seconds}s",
        "next_step": "Next Step",
        "back": "Back",
        "send_code": "Send Code",
        "safety_verify": "Security Verification",
        "code_sent": "Verification code sent to your Phone/Telegram",
        "running_logs": "Running Logs",
        "logs_summary": "Showing last {count} entries ({days} Days History)",
        "export_logs": "Export Logs",
        "no_logs": "No logs available",
        "task_label": "Task",
        "bot_reply": "Bot Reply",
        "task_exec_success": "executed successfully",
        "task_exec_failed": "execution failed",
        "close": "Close",
        "success": "Success",
        "failure": "Failure",
        "task_details": "Task Details",
        "manage_tasks_for": "Manage automatic sign-in tasks for account",
        "refresh_chats": "Refresh Chats",
        "loading": "Loading...",
        "no_tasks": "Configure Your First Task",
        "no_tasks_desc": "Select a channel or group, set actions and timing",
        "create_task": "Create Task",
        "edit_task": "Edit Task",
        "task_name": "Task Name",
        "task_name_placeholder": "e.g. linuxdo_sign",
        "task_name_required": "Please enter a task name",
        "cron_required": "Please enter a CRON expression",
        "range_required": "Please enter a full time range",
        "chat_required": "Please add at least one chat",
        "select_chat_error": "Please select a chat",
        "add_action_error": "Please add at least one action",
        "load_failed": "Load failed",
        "account_session_invalid": "Account session expired, please login again",
        "create_success": "Task created",
        "create_failed": "Create failed",
        "associated_account": "Associated Account",
        "define_global_rules": "Define global sign-in rules that apply to multiple targets",
        "basic_config": "Basic Configuration",
        "scheduling_mode": "Scheduling Mode",
        "mode_range": "Random Window",
        "mode_fixed": "Cron",
        "random_range_default": "Random Range (Default)",
        "random_range_desc": "The system randomly selects a time within the configured range to avoid bot detection.",
        "fixed_cron_desc": "Use a standard Cron expression to set an exact execution time, e.g. 0 9 * * * = every day at 09:00",
        "cron_expression": "Cron Expression",
        "cron_placeholder": "0 9 * * *",
        "start_time": "Start Time",
        "end_time": "End Time",
        "start_label": "Start",
        "end_label": "End",
        "time_range": "Time Range",
        "target_chat_config": "Target Chat Configuration",
        "add_chat": "Add Chat",
        "no_target_chat": "No target chats yet",
        "actions_count": "Actions",
        "id_label": "ID",
        "deploy_task": "Create Task",
        "configure_target_chat": "Configure Target Chat",
        "select_target_chat": "Select Target Chat",
        "select_chat_placeholder": "Select from server chats...",
        "action_sequence_title": "Action Sequence",
        "add_sign_action": "Add Sign Action",
        "no_actions_hint": "Click the button above to add the first action, e.g. \"/checkin\"",
        "confirm_add": "Confirm Add",
        "random_range_recommend": "Random Range (Recommended)",
        "fixed_time_cron": "Fixed Time (Cron)",
        "sign_time_cron": "Sign-in Time (Cron Expression)",
        "cron_example": "Example: 0 9 * * * (9:00 AM)",
        "refresh_list": "Refresh",
        "refresh_chat_title": "Re-fetch chats from Telegram",
        "select_from_list": "Select from list...",
        "search_chat": "Search Chats",
        "search_chat_placeholder": "Name / Username / Chat ID",
        "searching": "Searching...",
        "search_no_results": "No matching chats",
        "ai_vision_mode": "AI Vision Mode",
        "ai_logic_solver": "AI Logic Solver",
        "ai_vision_click_mode": "AI Vision Click",
        "ai_vision_send_mode": "AI Vision Send",
        "ai_logic_send_mode": "AI Math Send",
        "ai_logic_click_mode": "AI Math Click",
        "sign_time": "Sign-in Time (CRON)",
        "random_delay": "Random Delay (Minutes)",
        "action_interval": "Action Interval (Seconds)",
        "select_chat": "Select Channel/Group",
        "manual_chat_id": "Or Manual Chat ID",
        "delete_after": "Message Deletion Delay (Sec, Optional)",
        "action_sequence": "Action Sequence",
        "deploy_now": "Deploy Now",
        "save_changes": "Save Changes",
        "add_action": "Add Action",
        "change_username": "Change Username",
        "new_username": "New Username",
        "current_password": "Current Password",
        "change_password": "Change Password",
        "old_password": "Old Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "2fa_settings": "Two-Factor Auth",
        "2fa_enable_desc": "Once on, you’ll enter a 6-digit code from your authenticator app along with your password.",
        "start_setup": "Start Setup",
        "scan_qr": "Scan the QR Code",
        "scan_qr_desc": "Scan the code above with Google Authenticator or a similar app.",
        "backup_secret": "Backup Key",
        "verify_code": "Verification Code",
        "verify": "Verify",
        "disable_2fa": "Turn Off 2FA",
        "ai_config": "AI",
        "api_key": "API Key",
        "base_url": "Base URL",
        "model": "Default Model",
        "test_connection": "Test Connection",
        "global_settings": "General",
        "sign_interval": "Sign-in Interval (Sec)",
        "sign_interval_desc": "Applies to all tasks with global interval enabled",
        "log_retention": "Log Retention (Days)",
        "save_global_params": "Save Global Parameters",
        "tg_api_config": "Telegram API",
        "restore_default": "Restore Default",
        "api_id": "API ID",
        "api_hash": "API Hash",
        "apply_api_config": "Apply API Config",
        "tg_config_warning": "Changing this can sign out existing accounts. Only customize it if adding an account fails with an API error.",
        "backup_migration": "Backup & Migration",
        "export_config": "Export All Config",
        "export_desc": "Includes all tasks and basic account info. The file contains sensitive data—keep it safe.",
        "download_json": "Download Config File",
        "import_config": "Import Config Content",
        "paste_json": "Or paste JSON here",
        "overwrite_conflict": "Replace Tasks with Same Name",
        "execute_import": "Import",
        "action_send_text": "Send Text",
        "action_send_dice": "Send Dice",
        "action_click_button": "Click Button",
        "action_ai_vision": "AI Image Recognition",
        "action_ai_logic": "AI Math Solver",
        "action_ai_vision_click": "AI Vision Click Button",
        "action_ai_vision_send": "AI Vision Send Text",
        "action_ai_logic_send": "AI Math Send Text",
        "action_ai_logic_click": "AI Math Click Button",
        "action_type_label": "Action {index} type",
        "dice_type_label": "Dice Type",
        "ai_auto_hint": "AI handles automatically, no extra config needed",
        "ai_hint_4": "Waits for a bot message with an image and buttons — AI identifies the image and clicks the matching option",
        "ai_vision_question_label": "AI Hint (Optional)",
        "ai_vision_question_placeholder": "Supplement the question context for AI; leave blank to auto-extract from message caption",
        "ai_hint_5": "Waits for a bot message with a math problem — AI solves it and sends the answer as text",
        "ai_hint_6": "Waits for a bot message with an image — AI reads the text in the image and sends it",
        "ai_hint_7": "Waits for a bot message with a math problem — AI solves it and clicks the matching button",
        "first_action_must_be_send": "The first action must be \"Send Text\" or \"Send Dice\"",
        "test_send_label": "Send Test Message",
        "test_send_btn": "Send Test",
        "test_send_hint": "The message will be sent via the selected account — use this to verify the Chat ID is correct",
        "test_send_success": "Test message sent",
        "test_send_failed": "Test send failed",
        "test_chat_btn": "Run Test",
        "test_chat_success": "Test run complete",
        "test_chat_failed": "Test run failed",
        "edit_chat_btn": "Edit Chat Config",
        "task_next_run": "Next Run",
        "next_run_today": "Today",
        "next_run_tomorrow": "Tomorrow",
        "next_run_in_window": "In window",
        "next_run_paused": "Paused",
        "next_run_unknown": "—",
        "ignore_case": "Ignore Case",
        "push_telegram": "TG Bot Notify",
        "push_forward": "Forward to Chat",
        "push_bark": "Bark Push",
        "push_custom": "Custom URL",
        "push_continue": "Continue Chat",
        "bark_url_label": "Bark URL",
        "forward_chat_id_label": "Forward Target Chat ID",
        "continue_chat_id_label": "Continue Chat ID",
        "placeholder_msg": "Message to send...",
        "placeholder_btn": "Text on button to click...",
        "manual_id_placeholder": "Manual Chat ID...",
        "delete_after_placeholder": "Auto-delete delay after sending...",
        "no_data": "No Data",
        "account_name_phone_required": "Please fill in account name and phone number",
        "account_name_duplicate": "Account name already exists. Please change it.",
        "send_code_failed": "Failed to send code",
        "login_code_required": "Please enter code",
        "account_name_required": "Please enter account name",
        "verify_failed": "Verification failed",
        "confirm_delete_account": "Are you sure you want to delete account {name}?",
        "account_deleted": "Account deleted",
        "delete_failed": "Delete failed",
        "save_failed": "Save failed",
        "qr_create_failed": "Failed to create QR",
        "cancel_failed": "Cancel failed",
        "logs_fetch_failed": "Failed to get logs",
        "clear_logs": "Clear Logs",
        "clear_logs_confirm": "Clear logs for account {name}?",
        "clear_logs_success": "Logs cleared",
        "clear_logs_failed": "Failed to clear logs",
        "qr_expired_not_found": "QR expired or not found",
        "qr_login_failed": "QR login failed",
        "qr_status_failed": "Failed to get QR status",
        "qr_password_required": "2FA password required",
        "qr_password_missing": "Please enter your 2FA password",
        "qr_password_invalid": "Incorrect 2FA password",
        "qr_password_submit": "Submit Password",
        "account_name_placeholder": "Letters and digits",
        "phone_number_placeholder": "+86 138 0000 0000",
        "qr_alt": "QR Code",
        "task_deleted": "Task {name} deleted",
        "task_run_failed": "Task run failed",
        "task_run_success": "Task {name} succeeded",
        "account_name_prompt": "Please enter account name",
        "status_active": "Active",
        "status_paused": "Paused",
        "task_schedule": "Schedule",
        "task_channels": "Target Chats",
        "task_hits": "{count} chats",
        "task_last_run": "Last Run",
        "task_run_logs_title": "Task Logs: {name}",
        "task_history_logs": "Task History",
        "task_history_logs_title": "Task History: {name}",
        "task_history_empty": "No check-in history yet",
        "task_history_no_flow": "No detailed flow for this record (older versions may only keep result)",
        "task_history_truncated": "Log was truncated. Original lines: {count}",
        "task_history": "History",
        "task_history_title": "History · {name}",
        "task_run_detail_title": "Run details · {name}",
        "view_live_logs": "View live logs",
        "task_logs_empty": "No execution logs",
        "manual_run": "Run Now",
        "start_task": "Start Scheduler",
        "stop_task": "Stop Scheduler",
        "task_started": "Scheduler started: {name}",
        "task_stopped": "Scheduler stopped: {name}",
        "task_toggle_failed": "Failed to toggle task state",
        "logs_waiting": "Waiting for logs...",
        "task_running": "Running...",
        "task_done": "Task completed",
        "task_executing": "Executing...",
        "chats_refreshed": "Chat list refreshed",
        "refresh_failed": "Refresh failed",
        "search_failed": "Search failed",
        "chat_id_numeric": "Chat ID must be a number",
        "update_success": "Task updated",
        "update_failed": "Update failed",
        "chat_default_name": "Chat {id}",
        "form_incomplete": "Please fill in all information",
        "username_changed": "Username changed successfully",
        "change_failed": "Failed to change",
        "password_mismatch": "Passwords do not match",
        "password_changed": "Password changed successfully",
        "default_password_warning": "You are still using the default password admin123, so anyone can sign in to this panel. Change it now.",
        "setup_failed": "Setup failed",
        "two_factor_enabled": "2FA enabled",
        "enable_failed": "Enable failed",
        "two_factor_disable_prompt": "Enter 2FA code to disable:",
        "two_factor_disabled": "2FA disabled",
        "disable_failed": "Disable failed",
        "export_success": "Config exported",
        "export_failed": "Export failed",
        "import_empty": "Please paste config",
        "import_success": "Import successful",
        "import_failed": "Import failed",
        "ai_save_success": "AI config saved",
        "connect_failed": "Connect failed",
        "test_failed": "Test error",
        "confirm_delete_ai": "Are you sure you want to delete AI config?",
        "ai_delete_success": "AI config deleted",
        "global_save_success": "Global settings saved",
        "telegram_save_success": "Telegram config saved",
        "confirm_reset_telegram": "Are you sure you want to reset Telegram config to default?",
        "config_reset": "Config reset",
        "operation_failed": "Operation failed",
        "new_username_placeholder": "New Username",
        "current_password_placeholder": "Verify Current Password",
        "status_enabled": "On",
        "status_disabled": "Off",
        "totp_code_placeholder": "6 digits",
        "delete_ai_config": "Delete AI config",
        "ai_base_url_placeholder": "https://api.openai.com/v1",
        "api_key_keep_hint": "Leave empty to keep the current API key",
        "sign_interval_placeholder": "Leave blank for random 1-120 seconds",
        "data_dir": "Data Directory",
        "data_dir_placeholder": "e.g. /opt/tg-signpulse-data",
        "data_dir_desc": "Used for sessions, logs, database, and task files",
        "data_dir_restart_hint": "Restart the backend service to apply.",
        "global_proxy": "Global Proxy",
        "global_proxy_placeholder": "socks5://127.0.0.1:1080 or http://127.0.0.1:7890",
        "global_proxy_desc": "Used for sign-in, session refresh, and tasks when an account has no proxy of its own.",
        "telegram_bot_notify": "Bot Notifications",
        "telegram_bot_notify_desc": "Get a message from your Telegram bot when a task fails or a keyword matches.",
        "telegram_bot_events_off_hint": "Turn on notifications above to use these.",
        "telegram_bot_master_switch": "Notifications",
        "telegram_login_notify": "Login Notifications",
        "telegram_login_notify_desc": "Send a Telegram message with the login IP on every login",
        "telegram_task_failure_notify": "Task Failure Notifications",
        "telegram_task_failure_notify_desc": "Send recent run logs when a task fails",
        "telegram_task_success_notify": "Task Success Notifications",
        "telegram_task_success_notify_desc": "Send a notification when a task succeeds",
        "telegram_bot_token": "Bot Token",
        "telegram_bot_token_placeholder": "Token from BotFather",
        "telegram_bot_chat_id": "Notify Chat ID",
        "telegram_bot_chat_id_placeholder": "e.g. 123456789",
        "telegram_bot_thread_id": "Notify Topic ID (Optional)",
        "telegram_bot_thread_id_placeholder": "Set when notifying a specific topic",
        "keyword_monitor": "Keyword Monitor",
        "keyword_monitor_desc": "Listen to a target group and push matched message text with its link",
        "monitor_account": "Monitor Account",
        "select_account": "Select account",
        "monitor_chat_id": "Target Chat ID",
        "monitor_chat_id_placeholder": "e.g. -1001234567890 or @channel",
        "monitor_keywords": "Keywords",
        "monitor_keywords_placeholder": "One keyword per line, comma-separated also works",
        "match_mode": "Match Mode",
        "match_contains": "Contains",
        "match_exact": "Exact",
        "match_regex": "Regex",
        "push_channel": "Push Channel",
        "custom_push_url": "Custom Push URL",
        "custom_push_url_placeholder": "POST JSON, or use {title}, {body}, {url} placeholders for GET",
        "topic_id_label": "Topic / Thread ID (Optional)",
        "topic_id_placeholder": "Topic ID for forum groups; leave blank if unused",
        "export_all_tasks": "Export All Tasks to Clipboard",
        "copy_all_tasks_success": "All tasks copied to clipboard",
        "copy_all_tasks_empty": "No tasks to export for this account",
        "copy_all_tasks_failed": "Failed to export all tasks",
        "paste_all_tasks_success": "Import complete; duplicate tasks were skipped",
        "relogin": "Re-login",
        "tg_api_id_placeholder": "From my.telegram.org",
        "tg_api_hash_placeholder": "From my.telegram.org",
        "github_repo": "GitHub Repository",
        "totp_placeholder": "Skip if disabled",
        "switch_to_english": "Switch to English",
        "switch_to_chinese": "Switch to Chinese",
        "switch_to_light": "Switch to Light Mode",
        "switch_to_dark": "Switch to Dark Mode",
        "tab_tasks": "Tasks",
        "tab_accounts": "Accounts",
        "tab_settings": "Settings",
        "main_navigation": "Main navigation",
        "confirm": "OK",
        "done": "Done",
        "optional": "Optional",
        "required": "Required",
        "copy": "Copy",
        "copied": "Copied",
        "refresh": "Refresh",
        "retry": "Try Again",
        "more_actions": "More actions",
        "unit_seconds": "sec",
        "unit_days": "days",
        "status_on": "On",
        "status_off": "Off",
        "configured": "Configured",
        "not_configured": "Not set up",
        "not_set": "Not set",
        "next_short": "Next",
        "next_run_none": "Not scheduled",
        "random_suffix": "random",
        "schedule_daily": "Daily at {time}",
        "schedule_daily_range": "Daily, random {start}–{end}",
        "task_status": "Scheduled",
        "delete_task": "Delete Task",
        "delete_task_title": "Delete “{name}”?",
        "delete_task_message": "This can’t be undone.",
        "run_connection_lost": "Lost connection to the server. Check the history later for the result.",
        "run_result_success": "Succeeded",
        "run_result_failed": "Failed",
        "run_result_unknown": "Finished",
        "today_summary": "Today",
        "summary_failed": "Failed",
        "summary_pending": "Pending",
        "summary_success": "Succeeded",
        "filter_account": "Account: {name}",
        "clear_filter": "Clear filter",
        "filter_empty": "No matching tasks",
        "show_all": "Show All",
        "load_failed_desc": "Make sure the backend service is running, then try again.",
        "empty_no_account_title": "Add a Telegram account first",
        "empty_no_account_desc": "Sign in with a phone code or QR code, then create check-in tasks for it.",
        "empty_no_task_title": "No check-in tasks yet",
        "empty_no_task_desc": "Create a task, then pick the chats to check in and when to run.",
        "import_from_clipboard": "Import from Clipboard",
        "import_from_clipboard_desc": "Paste task config you exported earlier",
        "export_all": "Export All Tasks",
        "export_all_desc": "Copy task config to the clipboard for backup or migration",
        "account_invalid_banner": "{name} is signed out",
        "account_invalid_action": "Its tasks can’t run. Tap to sign in again.",
        "account_required": "Please choose an account",
        "no_account_yet": "No accounts yet. Add one first.",
        "cron_fields_hint": "min hour day month weekday",
        "cron_examples": "Examples",
        "target_chats_count": "Target Chats ({count})",
        "target_chats_hint": "The task runs its actions in each of these chats, in order.",
        "no_target_chat_desc": "Add a channel, group, or bot, and set the actions to run there.",
        "chat_row_meta": "Actions: {count}",
        "test_chat_named": "Test {name}",
        "edit_locked_hint": "Task name and account can't be changed after creation.",
        "test_short": "Test",
        "save_success": "Saved",
        "field_chat": "Chat",
        "field_message": "Message",
        "field_button_text": "Button text",
        "chat_search_hint": "Search by name, username, or ID. If a chat isn’t listed, enter its ID below.",
        "topic_id_short": "Topic ID",
        "action_sequence_count": "Actions ({count})",
        "action_sequence_hint": "Actions run from top to bottom.",
        "remove_action": "Remove action {index}",
        "remove_chat": "Remove Chat",
        "remove_chat_title": "Remove “{name}”?",
        "account_task_count": "{count} tasks",
        "home_headline_failed": "{count} tasks failed today",
        "home_headline_failed_one": "{count} task failed today",
        "home_headline_relogin": "{count} accounts need to sign in again",
        "home_headline_relogin_one": "{count} account needs to sign in again",
        "home_headline_ok": "All good today",
        "home_headline_no_account": "Add a Telegram account to begin",
        "home_headline_no_task": "No check-in tasks yet",
        "home_headline_error": "Can’t reach the server",
        "home_headline_filtered": "{name} is all good today",
        "home_updated": "Updated {time}",
        "home_task_total": "{count} tasks",
        "pulse_caption": "Last 30 days · {rate} success",
        "pulse_rate_title": "30-day success rate · {count} runs",
        "pulse_rate_label": "30-day success rate",
        "pulse_today": "Today",
        "pulse_days_short": "30 days",
        "pulse_days_ago": "{count} days ago",
        "pulse_day_detail": "{date}: {up} succeeded, {down} failed",
        "pulse_day_empty": "{date}: no runs",
        "pulse_label": "Daily results for the last 30 days",
        "retry_run": "Retry",
        "upcoming_title": "Up next",
        "upcoming_now": "Now",
        "upcoming_in_window": "{names} in its random window",
        "upcoming_empty": "Nothing scheduled for today or tomorrow",
        "upcoming_skip_warn": "{name} must sign in again or this is skipped",
        "account_ok": "OK",
        "account_failed_count": "{count} failed",
        "account_invalid_tasks": "{count} tasks paused. They resume after you sign in again.",
        "account_invalid_no_tasks": "Sign in again before tasks can run",
        "manage_accounts": "Manage Accounts",
        "account_no_tasks": "No tasks yet",
        "account_no_runs": "No runs in the last 30 days",
        "needs_relogin": "Sign-in needed",
        "account_invalid_title": "Signed out",
        "account_invalid_desc": "The Telegram session expired or was revoked, so this account’s tasks can’t run. Sign in again to restore them.",
        "account_status": "Status",
        "last_checked": "Last checked",
        "delete_account": "Delete Account",
        "delete_account_title": "Delete “{name}”?",
        "delete_account_message": "This removes the account’s sign-in session. You’ll need to sign in again to use it.",
        "delete_account_message_tasks": "This account still has {count} tasks. They won’t be able to run after the account is deleted.",
        "account_saved": "Account saved",
        "proxy_hint": "Use socks5:// or http://. Leave blank to use the global proxy.",
        "health_check": "Check account status",
        "health_check_short": "Check",
        "health_check_done": "Account status updated",
        "health_check_failed": "Status check failed",
        "accounts_subtitle": "{count} accounts",
        "accounts_subtitle_invalid": "{count} accounts · {invalid} need sign-in",
        "accounts_footer": "Tap an account to see details, sign in again, or view logs.",
        "field_account_name": "Name",
        "field_phone": "Phone",
        "field_code": "Code",
        "field_2fa": "2FA",
        "field_proxy": "Proxy",
        "field_remark": "Note",
        "relogin_intro": "“{name}” is signed out. Its tasks resume after you sign in again.",
        "login_method": "Sign-in method",
        "login_phone_hint": "Include the country code, e.g. +14155550123.",
        "optional_settings": "Optional",
        "login_optional_hint": "Only needed if the Telegram account has two-step verification. Leave the proxy blank to use the global proxy.",
        "login_qr_hint": "Scan with a phone that’s already signed in to Telegram.",
        "qr_steps": "Open Telegram › Settings › Devices › Link Desktop Device",
        "resend_code": "Resend",
        "confirm_login": "Sign In",
        "telegram_bot_test_required": "Enter the token and chat ID first",
        "telegram_bot_section_bot": "Bot",
        "telegram_bot_token_short": "Token",
        "telegram_bot_chat_id_short": "Chat ID",
        "telegram_bot_send_test": "Send Test Message",
        "telegram_bot_section_events": "Notify me about",
        "appearance": "Appearance",
        "theme": "Theme",
        "theme_system": "System",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "language": "Language",
        "account_security": "Account & Security",
        "features": "Features",
        "data": "Data",
        "about": "About",
        "built_at": "Built",
        "software_update": "Software Update",
        "update_in_progress_short": "Updating",
        "update_checking": "Checking for updates",
        "update_check_failed": "Check failed",
        "update_available_short": "Update",
        "update_latest_short": "Up to date",
        "update_available_title": "Update available",
        "update_latest_version": "Latest version v{version}",
        "update_new_build": "A newer build is in the registry",
        "update_latest_title": "You're up to date",
        "update_unknown_title": "Can't tell if there's an update",
        "update_unknown_desc": "GitHub or the image registry is unreachable. Try again later.",
        "update_check_disabled": "Update checks are turned off with APP_UPDATE_CHECK",
        "update_check_failed_desc": "Couldn't get update info. Check the network and try again.",
        "update_checked_at": "Last checked {time}",
        "update_view_changes": "See What's New",
        "update_restart_hint": "The panel downloads the new version and restarts itself. It's unavailable for about a minute, and scheduled tasks resume afterwards.",
        "update_local_build_hint": "This image was built locally; updating switches to the registry version.",
        "update_now": "Update Now",
        "update_try": "Check and Update",
        "update_recheck": "Check Again",
        "update_reload_page": "Reload Page",
        "update_confirm_title": "Update now?",
        "update_confirm_message": "The panel downloads the new version and restarts. It's unavailable for about a minute.",
        "update_step_pull": "Download new version",
        "update_step_restart": "Restart panel",
        "update_step_done": "Done",
        "update_restarting_desc": "The panel is restarting. This page reloads when it's back.",
        "update_rolled_back_desc": "The new version didn't start, so the previous version was restored.",
        "update_timeout_desc": "This is taking a while. Reload the page later to see the result.",
        "update_start_failed": "Update failed. Try again later.",
        "update_reloading": "Updated. Reloading",
        "update_tasks_running": "A task is running. Update after it finishes.",
        "update_done_toast": "Updated to v{version}",
        "update_manual_title": "Update on the Server",
        "update_manual_desc": "Run this in the folder with docker-compose.yml:",
        "update_manual_not_container": "The panel's Docker container wasn't found. Update it the way you deployed it, for example pull the latest code and restart.",
        "update_enable_title": "Turn On One-Click Update",
        "update_enable_desc": "Add this line under volumes in docker-compose.yml, then redeploy:",
        "update_enable_risk": "This lets the panel manage Docker on this machine. Use a strong password and turn on two-factor authentication.",
        "update_reason_disabled": "One-click update is turned off with APP_SELF_UPDATE.",
        "update_reason_no_socket": "The Docker socket isn't mounted, so one-click update isn't available.",
        "update_reason_permission": "The panel can't read or write the Docker socket.",
        "update_reason_unreachable": "Can't reach Docker. Check the socket path or DOCKER_HOST.",
        "update_reason_not_container": "If the panel does run in a container, set its name with APP_UPDATE_CONTAINER.",
        "update_reason_pinned": "The container uses an image pinned by digest. Switch to an image tag in compose and redeploy.",
        "update_reason_not_pullable": "The current image isn't available from a registry, so the panel can't download new versions. For a private image, log in to the registry on the server and update manually.",
        "update_pull_denied": "The image isn't in the registry, or the registry requires a login",
        "update_manual_rebuild_desc": "If you built the image yourself, pull the latest code and rebuild:",
        "needs_change": "Change needed",
        "default_password_title": "Change the default password",
        "logout_confirm": "Log out?",
        "export_file_success": "Config file downloaded",
        "change_username_hint": "Use the new username the next time you log in.",
        "password_hint": "At least 6 characters.",
        "confirm_password_short": "Confirm",
        "confirm_password_placeholder": "Re-enter new password",
        "verify_and_enable": "Verify & Turn On",
        "2fa_disable_desc": "Enter the 6-digit code from your authenticator to turn off two-factor authentication. After that, only your password is needed to log in.",
        "ai_config_desc": "Used by the AI image and math actions. Works with OpenAI-compatible APIs.",
        "ai_test_hint": "Sends a test request with the saved settings.",
        "sign_interval_short": "Interval",
        "log_retention_short": "Keep logs",
        "tg_api_custom": "Using custom credentials",
        "tg_api_default": "Using built-in credentials",
        "tg_api_custom_short": "Custom",
        "tg_api_default_short": "Default",
        "tg_api_hint": "Get these from API development tools at my.telegram.org.",
        "import_desc": "Export your current config first as a backup.",
        "overwrite_conflict_desc": "When off, tasks with the same name are skipped. When on, they’re replaced.",
        "login_tagline": "Automatic check-ins for your Telegram accounts",
        "login_fields_required": "Enter your username and password",
        "totp_short": "2FA code",
        "totp_if_enabled": "If enabled",
        "connect_success": "Connected",
        "upload_json": "Choose JSON File"
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLangState] = useState<Language>('zh');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        try {
            const savedLang = localStorage.getItem('tg-signer-lang');
            if (savedLang === 'zh' || savedLang === 'en') {
                setLangState(savedLang);
            }
        } catch {
            // localStorage 不可用时使用默认语言
        }
        setMounted(true);
    }, []);

    useEffect(() => {
        document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
    }, [language]);

    const setLanguage = useCallback((lang: Language) => {
        setLangState(lang);
        try {
            localStorage.setItem('tg-signer-lang', lang);
        } catch {
            // 忽略存储失败
        }
    }, []);

    const t = useCallback((key: string) => {
        return translations[language][key] || key;
    }, [language]);

    const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
